# We subsample 20 times, with replacement, and check if the fitting results are comparable to each other

In [1]:
%run -i ~/project/preambles
%run -i ~/project/helper_functions
%run -i ~/project/fitting_functions

In [2]:
# # Global parameters:
number_of_cycles = 500 # how many passes through the training data we go through
number_of_groups = 1 # divide the data set into smaller ones, to make fitting easier.
steps_per_batch = 5
dims = 2  # 2D spatial
head = 1000 # how many to down/subsample to.

In [3]:
gene_list = [ "Inha", "Inhba", "Inhbb", "Fst", "Esr1", "Esr2", "Pgr", "Ar", "Cyp19a1", 
    "Cyp17a1", "Cyp11a1", "Lhcgr", "Parm1", "Akr1c18", "Fshr", "Star", "Ptgfr", 
    "Sfrp4", "Acvr1", "Acvr2a", "Acvr2b", "Ghr", "Lhb", "Cga"]
# gene_list = [ "Inha"]
# puck_list = 'all'
puck_list = ['Puck_230517_39'] # the largest puck

adata, X,Y,df, gene_list=load_data(gene_list=gene_list, head=head, puck_list = puck_list)
df

,x,y,Inha,Inhba,Inhbb,Fst,Esr1,Esr2,Pgr,Ar,...,Fshr,Star,Ptgfr,Sfrp4,Acvr1,Acvr2a,Acvr2b,Ghr,Lhb,Cga
GCCTATGGTAGAAC-1-2,3.0079,1.4262,0.608417,0.00000,1.468906,0.0,0.0,0.0,0.0,0.000000,...,0.0,1.067602,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
ACCNTTTGAATGCG-1-2,2.9178,2.3609,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
GGGGAGGGAGGACC-1-2,3.9281,2.4019,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TTCCAACAACGGAA-1-2,1.6823,2.9786,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
AACGTAGTCGGTTC-1-2,1.9859,3.0400,0.608417,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,2.666732,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AGCTACCCCCCTTT-1-2,4.0152,2.0904,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,1.067602,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TGTTGCATGCCTAT-1-2,3.8677,2.4314,0.000000,0.00000,1.468906,0.0,0.0,0.0,0.0,2.279514,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TGCCANTATATGTA-1-2,2.8842,2.3842,0.000000,1.88979,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
GTCATCTCTTACAT-1-2,2.5740,2.2334,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,1.905860,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
GGTGCAGGCCTCCG-1-2,3.6570,4.1917,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
head = 50 # how many locations to consider in the real data set.
estimated_params_df = pd.DataFrame()
for _ in range(25): # sub sampling with replacement the top head rows
    try:
        adata, X,Y,df=load_data(gene_list=gene_list, head=head, puck_list = puck_list)
        torch.autograd.set_detect_anomaly(True)
        optimized_marginal_params = optimize_marginal_parameters(X, Y, number_of_groups,  number_of_cycles, steps_per_batch)
        alpha_matrix, nu_matrix, sigma_matrix = optimize_cross_parameters(optimized_marginal_params,X,Y,number_of_groups,number_of_cycles,steps_per_batch)
        estimated_params_df = pd.concat([estimated_params_df, store_as_df(alpha_matrix, nu_matrix, sigma_matrix) ], ignore_index=True)
    except Exception as e:
        print(e)
        continue
estimated_params_df

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

epoch 0 step 1 succeeded with learning rate: 6.25e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4']

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

epoch 0 step 1 succeeded with learning rate: 6.25e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4']

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

epoch 0 step 1 succeeded with learning rate: 6.25e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4']

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

Condition failed at epoch 0, halving learning rate. Attempt 5

epoch 0 step 1 succeeded with learning rate: 3.125e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4', 'Epoch 0: LR halved at attempt 5']

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

Condition failed at epoch 0, halving learning rate. Attempt 5

epoch 0 step 1 succeeded with learning rate: 3.125e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4', 'Epoch 0: LR halved at attempt 5']

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

Condition failed at epoch 0, halving learning rate. Attempt 5

epoch 0 step 1 succeeded with learning rate: 3.125e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4', 'Epoch 0: LR halved at attempt 5']

,alpha_matrix_11,nu_matrix_11,sigma_matrix_11,alpha_matrix_12,nu_matrix_12,sigma_matrix_12,alpha_matrix_13,nu_matrix_13,sigma_matrix_13,alpha_matrix_14,...,sigma_matrix_2224,alpha_matrix_2323,nu_matrix_2323,sigma_matrix_2323,alpha_matrix_2324,nu_matrix_2324,sigma_matrix_2324,alpha_matrix_2424,nu_matrix_2424,sigma_matrix_2424
0,0.072879,3.646917,0.491468,0.901475,3.275655,-8.411848e-33,0.902136,4.554169,-3.854409e-32,0.901638,...,-1.749053e-33,0.861975,2.879451,2.220446e-16,1.246195,3.809958,-1.231285e-33,0.861975,2.879451,2.220446e-16
1,0.557146,0.022430,0.561104,1.039490,0.832399,-5.445879e-33,0.983671,1.016977,-4.607294e-33,1.000599,...,-4.879456e-33,0.875270,2.777824,2.220446e-16,1.255428,3.587826,-1.178727e-33,0.875270,2.777824,2.220446e-16
2,0.522648,0.023109,0.535217,0.997880,2.984254,-3.954633e-33,0.983425,0.834263,-6.013207e-33,0.980838,...,-4.812331e-33,0.851366,2.631094,2.220446e-16,1.238880,3.441097,-1.215556e-33,0.851366,2.631094,2.220446e-16
3,0.430453,0.022236,0.612119,1.013394,0.855412,-5.552825e-33,0.955058,1.952840,-3.215555e-33,0.954982,...,-1.773026e-33,0.882032,2.825522,2.220446e-16,1.260151,3.658864,-1.157565e-33,0.882032,2.825522,2.220446e-16
4,0.156946,3.917829,0.478084,0.916040,5.010055,-5.615177e-32,0.920114,4.600836,-3.009130e-32,0.909815,...,-4.443176e-33,0.876083,2.739788,2.220446e-16,1.255997,3.758140,-1.033419e-33,0.876083,2.739788,2.220446e-16
5,0.489680,0.023757,0.594137,0.969624,0.834557,-6.169391e-33,0.970993,3.217111,-5.593163e-33,0.991653,...,-1.833358e-33,0.856578,2.872271,2.220446e-16,1.242468,3.682273,-1.333227e-33,0.856578,2.872271,2.220446e-16
6,0.181814,2.952787,0.478955,0.915222,3.537210,-1.085537e-32,0.923389,3.841627,-1.425742e-32,0.913110,...,-4.786253e-33,0.873659,2.837090,2.220446e-16,1.257188,3.654314,-1.146815e-33,0.873659,2.837090,2.220446e-16
7,0.067737,2.356633,0.576217,0.901678,3.913574,-1.974791e-32,0.901635,3.911663,-1.970875e-32,0.901481,...,-1.594892e-33,0.917862,2.831673,2.220446e-16,1.285485,3.641674,-1.013141e-33,0.917862,2.831673,2.220446e-16
8,0.367287,0.236906,0.558546,0.949245,2.495317,-3.769703e-33,0.944992,2.770946,-4.526748e-33,0.940540,...,-4.568682e-33,0.883088,2.794826,2.220446e-16,1.263729,3.611969,-1.082449e-33,0.883088,2.794826,2.220446e-16
9,0.137874,2.223619,0.523388,0.910684,2.355475,-4.542000e-33,0.906196,3.779879,-1.615249e-32,0.905266,...,-1.654818e-33,0.884271,2.700949,2.220446e-16,1.261720,3.510953,-1.098979e-33,0.884271,2.700949,2.220446e-16
10,0.119388,2.370392,0.563769,0.916935,4.256524,-1.770460e-32,0.903951,2.803457,-4.789189e-33,0.903951,...,-3.341540e-33,0.884730,2.674103,2.220446e-16,1.262041,3.776514,-9.109241e-34,0.884730,2.674103,2.220446e-16
11,0.183608,2.884458,0.501305,0.941984,4.381089,-1.259948e-29,0.920229,3.602678,-1.117368e-32,0.919109,...,-4.781539e-33,0.867421,2.610333,2.220446e-16,1.252934,3.428009,-1.063056e-33,0.867421,2.610333,2.220446e-16
12,0.111717,2.480239,0.489468,0.905442,3.251284,-9.178752e-33,0.905466,3.299332,-9.621792e-33,0.905130,...,-1.064518e-33,0.891378,2.692503,2.220446e-16,1.266710,3.502506,-1.064518e-33,0.891378,2.692503,2.220446e-16
13,0.109568,1.659237,0.592645,0.908913,3.923218,-8.670568e-33,0.907769,3.461847,-5.641436e-33,0.936501,...,-2.587711e-20,0.846007,2.753108,2.220446e-16,1.238305,4.154390,-8.543542e-34,0.846007,2.753108,2.220446e-16
14,0.124056,2.466194,0.558993,0.911346,4.369150,-1.887638e-32,0.908581,3.528138,-7.580433e-33,0.905241,...,-4.291409e-33,0.865994,2.710608,2.220446e-16,1.248980,3.912321,-9.342563e-34,0.865994,2.710608,2.220446e-16
15,0.049469,2.075108,0.570400,0.904207,3.737576,-1.563255e-32,0.907928,3.811687,-1.652607e-32,0.957441,...,-5.425105e-33,0.844758,2.749170,2.220446e-16,1.234349,3.559171,-1.316654e-33,0.844758,2.749170,2.220446e-16
16,0.240189,0.426643,0.495350,0.919358,3.410890,-5.824813e-33,0.920255,3.488750,-6.189385e-33,0.915888,...,-4.466974e-33,0.862902,2.856139,2.220446e-16,1.246839,4.133048,-9.672305e-34,0.862902,2.856139,2.220446e-16
17,0.543049,0.023391,0.649253,0.985230,0.834062,-5.994590e-33,1.040723,0.834071,-5.417160e-33,0.992036,...,-1.747186e-33,0.854435,2.719919,2.220446e-16,1.240992,3.529926,-1.248902e-33,0.854435,2.719919,2.220446e-16
18,0.088009,2.462201,0.469049,0.907543,3.122537,-7.596424e-33,0.918273,2.181278,-3.865683e-33,0.942308,...,-4.809043e-33,0.861440,2.821437,2.220446e-16,1.248861,3.639997,-1.192976e-33,0.861440,2.821437,2.220446e-16
19,0.191368,2.008395,0.715866,0.910117,2.323600,-4.486996e-33,0.913626,2.853089,-6.122478e-33,0.910117,...,-5.096718e-33,0.864486,2.715737,2.220446e-16,1.247933,3.525740,-1.197304e-33,0.864486,2.715737,2.220446e-16
20,0.195619,2.400532,0.433269,0.918921,3.248261,-7.860902e-33,0.918804,3.340036,-8.593045e-33,0.919097,...,-5.270283e-33,0.838362,2.758269,2.220446e-16,1.233165,3.576014,-1.268798e-33,0.838362,2.758269,2.220446e-16
21,0.152204,2.550050,0.539782,0.909132,3.362529,-9.973170e-33,0.906588,3.996937,-2.096632e-32,0.906922,...,-4.603714e-33,0.889311,2.711254,2.220446e-16,1.265256,3.521255,-1.081715e-33,0.889311,2.711254,2.220446e-16
22,0.100232,2.027089,0.584827,0.904395,3.064414,-6.309173e-33,0.927103,2.029486,-3.340958e-33,0.906475,...,-1.115270e-33,0.864217,2.772615,2.220446e-16,1.247747,3.775553,-1.115270e-33,0.864217,2.772615,2.220446e-16
23,0.530215,0.022879,0.474478,1.008519,0.832901,-5.753389e-33,1.024209,0.833601,-5.584771e-33,0.974969,...,-4.911616e-33,0.876659,2.593179,2.220446e-16,1.256396,3.403181,-1.084646e-33,0.876659,2.593179,2.220446e-16
24,0.358814,0.026637,0.521248,0.957674,1.121833,-4.775915e-33,0.937928,2.954305,-4.290346e-33,0.935080,...,-3.957058e-33,0.865936,2.662380,2.220446e-16,1.248938,3.759324,-9.842998e-34,0.865936,2.662380,2.220446e-16

In [5]:
df_to_plot = estimated_params_df
%run -i epilogue

DataFrame saved to /home/zc362/project/python_processed_data/fitted_parameters_0.csv